import Head from "next/head";
import { Container, Heading } from "@chakra-ui/react";

export default function Home() {
   return (
      <>
         <Head>
            <title>Next App Data Fetching</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <Container maxW="1200px">
               <Heading>Hello Dek</Heading>
            </Container>
         </main>
      </>
   );
}
